services:
  wx2tg:
    image: docker.io/xleat/wx2tg:latest
    container_name: wx2tg
    depends_on:
      - wx2tg-db
      - gewe
    env_file:
      - .env.docker
    volumes: # 示例，换成你的 volumes
      - ./storage:/app/storage
      - ./logs:/app/logs
    restart: unless-stopped

  gewe:
    image: docker.io/xleat/gewe:latest
    container_name: gewe
    volumes: # 示例，换成你的 volumes
      - ./temp:/root/temp
    restart: unless-stopped

  # 已经有数据库可以删除这个服务
  wx2tg-db:
    image: docker.io/postgres:17.4
    container_name: wx2tg-db
    restart: unless-stopped
    volumes: # 示例，换成你的 volumes
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wx2tg
      POSTGRES_PASSWORD: example # 记得修改 POSTGRES 的密码
      PGDATA: /var/lib/postgresql/data/pgdata



