name: Docker Image CI

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64/v8 ]
        include:
          - platform: linux/amd64
            QEMU_ARCH: x86_64
          - platform: linux/arm64/v8
            QEMU_ARCH: aarch64

    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.2.0
        with:
          node-version: 20.18.3

      - name: Cache Node.js modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ matrix.platform }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.platform }}-node-modules-    

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Build and push for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            xleat/wx2tg:latest
            xleat/wx2tg:${{ env.APP_VERSION }}
          platforms: linux/amd64,linux/arm64/v8  # Specify multiple platforms for the build
          cache-from: type=gha  # Use GitHub Actions cache
          cache-to: type=gha,mode=max  # Store cache for future runs

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: xleat/wx2tg
          readme-filepath: ./README.md
          short-description: 'telegram收发微信消息'
